name: ba_wiki_asset_tool
description: Tool for automating the extraction and conversion of Blue Archive assets
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.4

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  colorize: ^3.0.0
  path: ^1.9.1

dev_dependencies:
  lintorium: ^38.1.0
  lints: ^6.0.0
  test: ^1.25.6
